-- MySQL Script generated by MySQL Workbench
-- Thu Sep 28 10:05:39 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`persoon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`persoon` (
  `persoonId` INT UNSIGNED NOT NULL,
  `voorNaam` VARCHAR(60) NOT NULL,
  `achterNaam` VARCHAR(100) NOT NULL,
  `geboorteDatum` DATE NOT NULL,
  `geslacht` VARCHAR(10) NOT NULL,
  `geboorteStad` VARCHAR(50) NOT NULL,
  `nationaliteit` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`persoonId`),
  UNIQUE INDEX `persoonId_UNIQUE` (`persoonId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`adres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`adres` (
  `adresID` INT UNSIGNED NOT NULL,
  `straat` VARCHAR(255) NOT NULL,
  `huisNummer` INT NOT NULL,
  `postCode` VARCHAR(45) NOT NULL,
  `stad` VARCHAR(45) NOT NULL,
  `persoon_persoonId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`adresID`),
  UNIQUE INDEX `adresID_UNIQUE` (`adresID` ASC) VISIBLE,
  INDEX `fk_adres_persoon_idx` (`persoon_persoonId` ASC) VISIBLE,
  CONSTRAINT `fk_adres_persoon`
    FOREIGN KEY (`persoon_persoonId`)
    REFERENCES `mydb`.`persoon` (`persoonId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`conducteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`conducteur` (
  `idTrein` INT NOT NULL,
  `conducteurNaam` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idTrein`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`reiziger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reiziger` (
  `reizigerNaam` INT NOT NULL,
  `classType` VARCHAR(45) NULL DEFAULT NULL,
  `idTrein` INT NULL DEFAULT NULL,
  PRIMARY KEY (`reizigerNaam`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`trein`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trein` (
  `idTrein` INT NOT NULL,
  `treinType` VARCHAR(45) NOT NULL,
  `vertrekTijd` VARCHAR(45) NOT NULL,
  `aankomstTijd` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTrein`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`vlucht`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vlucht` (
  `vluchtnummer` INT NOT NULL,
  `vliegtuigType` VARCHAR(100) NULL DEFAULT NULL,
  `vertrekTijd` DATETIME NULL DEFAULT NULL,
  `aankomstTijd` DATETIME NOT NULL,
  `vertrekVluchtHaven` VARCHAR(120) NULL DEFAULT NULL,
  `aankomstVluchtHaven` VARCHAR(120) NULL DEFAULT NULL,
  PRIMARY KEY (`vluchtnummer`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
